### ISSUE TITLE
PropertRef generates extra Left Outer Join

### ISSUE THREAD

**Issue by fassadlr** [nhibernate/fluent-nhibernate#368]
Hi,

When specifying a PropertyRef on a HasMany to join onto another table the SQL that gets generated includes an extra left outer join which skews the result set.

**This relates to NHibernate's 4.1 release.**

I.e. I want to join table "House" to "People" but on "TaxNumber" and not ID:

HasMany(x => x.People).ForeignKeyConstraintName("none")
.KeyColumn("TaxNumber")
.PropertyRef("TaxNumber")
.Cascade.AllDeleteOrphan()
.Access.NoOp();

**Comment by chester89** [comment]
@fassadlr can you clarify? you seeing this only with NHibernate 4.1?

**Comment by fassadlr** [comment]
Hi @chester89!

This started happening when we upgraded our NHibernate version to 4.1 yes.

**Comment by mokasius** [comment]
Hello @fassadlr 
Did you solve the property-ref problem??
I'm having the same issue.

Thanks!

**Comment by fassadlr** [comment]
Hi @mokasius I dont really work with NHibernate any longer, sorry. But I dont think that issues was solved.

**Comment by mokasius** [comment]
Thanks for your reply @fassadlr !! I'm gonna find a way out, but really think that it isn't solved in this specific version.

**Comment by mokasius** [comment]
Hey @jonasbighetti I didn't find any good solution for this case. I just changed the query and used subQuery to do the job. Quite a work because i had to change all queries with this prop.
Hope u find anything better.

**Comment by jonasbighetti** [comment]
@mokasius could you show some example of what you did? I'm using DetachedCriteria to create some queries but it isn't giving me the results I expected.

**Comment by hazzik** [comment]
It seems this is general NHibernate question. Please ask on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers).
